version: 2
jobs: 
  build:
    docker: 
      - image: image: circleci/openjdk:9.0.4-jdk
    steps:
      - checkout
      - run: 
          name: build and test with production code
          command: ./gradlew build
      - run: 
          name: save test results
          command: mkdir -p ~/junit/
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
